name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        node:
        - 16
        - 14
        - 12
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install --frozen-lockfile
    - run: yarn audit
    - run: yarn test
